import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, "..");

const questsDir = path.join(rootDir, "Quests");
const informationDir = path.join(rootDir, "Information");
const questsDataFile = path.join(rootDir, "src", "QuestsData.ts");
const informationDataFile = path.join(rootDir, "src", "InformationData.ts");

interface BuildModuleOptions {
  exportName: string;
  importRoot: string;
  files: string[];
}

interface QuestDirNode {
  name: string;
  metaAlias: string | null;
  files: Map<string, string>;
  children: Map<string, QuestDirNode>;
}

function toIdentifier(value: string): string {
  const cleaned = value.replace(/[^A-Za-z0-9_$]/g, "_");
  return /^[A-Za-z_$]/.test(cleaned) ? cleaned : `_${cleaned}`;
}

function normalizePath(value: string): string {
  return value.split(path.sep).join("/");
}

function toExportKey(relativePathWithoutExtension: string): string {
  return relativePathWithoutExtension.replace(/,/g, "-");
}

function escapeSingleQuotes(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/'/g, "\\'");
}

function createQuestDirNode(name: string): QuestDirNode {
  return {
    name,
    metaAlias: null,
    files: new Map<string, string>(),
    children: new Map<string, QuestDirNode>(),
  };
}

function ensureQuestDirNode(root: QuestDirNode, segments: string[]): QuestDirNode {
  let node = root;
  for (const segment of segments) {
    if (!node.children.has(segment)) {
      node.children.set(segment, createQuestDirNode(segment));
    }
    node = node.children.get(segment)!;
  }
  return node;
}

async function collectJsonFiles(dir: string, parentRelative = ""): Promise<string[]> {
  const entries = await fs.readdir(dir, { withFileTypes: true });
  const files: string[] = [];

  for (const entry of entries) {
    const relativePath = parentRelative ? path.join(parentRelative, entry.name) : entry.name;
    const fullPath = path.join(dir, entry.name);

    if (entry.isDirectory()) {
      const nestedFiles = await collectJsonFiles(fullPath, relativePath);
      files.push(...nestedFiles);
      continue;
    }

    if (!entry.isFile()) {
      continue;
    }

    if (path.extname(entry.name).toLowerCase() !== ".json") {
      continue;
    }

    files.push(relativePath);
  }

  return files;
}

function buildInformationModule({ exportName, importRoot, files }: BuildModuleOptions): string {
  const imports: string[] = [];
  const entries: string[] = [];
  const usedAliases = new Set<string>();
  const usedKeys = new Set<string>();

  for (const relativeFilePath of files) {
    const normalizedPath = normalizePath(relativeFilePath);
    const relativeWithoutExt = normalizedPath.replace(/\.json$/i, "");
    const alias = toIdentifier(`${exportName}_${relativeWithoutExt}`);
    const key = toExportKey(relativeWithoutExt);

    if (usedAliases.has(alias)) {
      throw new Error(`Duplicate generated import alias "${alias}" in ${exportName} data.`);
    }
    usedAliases.add(alias);

    if (usedKeys.has(key)) {
      throw new Error(`Duplicate generated export key "${key}" in ${exportName} data.`);
    }
    usedKeys.add(key);

    imports.push(`import ${alias} from '${importRoot}/${normalizedPath}' with { type: "json" };`);
    entries.push(`  '${key}': ${alias},`);
  }

  const header = [
    "// This file is auto-generated by scripts/generate-json-exports.ts.",
    "// Do not edit this file manually.",
    "",
  ].join("\n");

  return `${header}${imports.join("\n")}\n\nexport const ${exportName} = {\n${entries.join("\n")}\n} as const;\n`;
}

function renderQuestDirNode(node: QuestDirNode, indentLevel: number): string[] {
  const indent = "  ".repeat(indentLevel);
  const lines: string[] = [];

  if (node.metaAlias) {
    lines.push(`${indent}_meta: ${node.metaAlias},`);
  }

  const sortedChildren = [...node.children.values()].sort((a, b) => a.name.localeCompare(b.name));
  for (const child of sortedChildren) {
    const childEntries = renderQuestDirNode(child, indentLevel + 1);
    lines.push(`${indent}'${escapeSingleQuotes(child.name)}': {\n${childEntries.join("\n")}\n${indent}},`);
  }

  const sortedFiles = [...node.files.entries()].sort(([a], [b]) => a.localeCompare(b));
  for (const [fileStem, alias] of sortedFiles) {
    lines.push(`${indent}'${escapeSingleQuotes(fileStem)}': ${alias},`);
  }

  return lines;
}

function buildQuestSetBlock(setName: string, rootNode: QuestDirNode): string {
  const titleExpr = rootNode.metaAlias ? `${rootNode.metaAlias}.title ?? ""` : "''";
  const subTitleExpr = rootNode.metaAlias ? `${rootNode.metaAlias}.subTitle ?? ""` : "''";

  const entries = [
    `    title: ${titleExpr},`,
    `    subTitle: ${subTitleExpr},`,
    ...renderQuestDirNode(rootNode, 2),
  ];

  return `  '${escapeSingleQuotes(setName)}': {\n${entries.join("\n")}\n  },`;
}

async function buildQuestModule({ exportName, importRoot, files }: BuildModuleOptions): Promise<string> {
  const imports: string[] = [];
  const usedAliases = new Set<string>();
  const questSets = new Map<string, QuestDirNode>();

  for (const relativeFilePath of files) {
    const normalizedPath = normalizePath(relativeFilePath);
    const alias = toIdentifier(`${exportName}_${normalizedPath.replace(/\.json$/i, "")}`);

    if (usedAliases.has(alias)) {
      throw new Error(`Duplicate generated import alias "${alias}" in ${exportName} data.`);
    }
    usedAliases.add(alias);
    imports.push(`import ${alias} from '${importRoot}/${normalizedPath}' with { type: "json" };`);

    const segments = normalizedPath.split("/");
    const setName = segments[0]!;
    const fileName = segments[segments.length - 1]!;
    const fileStem = fileName.replace(/\.json$/i, "");

    if (!questSets.has(setName)) {
      questSets.set(setName, createQuestDirNode(setName));
    }

    const setRootNode = questSets.get(setName)!;
    const directoryNode = ensureQuestDirNode(setRootNode, segments.slice(1, -1));

    if (fileStem === "_meta") {
      directoryNode.metaAlias = alias;
    } else {
      directoryNode.files.set(fileStem, alias);
    }
  }

  const setBlocks = [...questSets.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([setName, rootNode]) => buildQuestSetBlock(setName, rootNode));

  const header = [
    "// This file is auto-generated by scripts/generate-json-exports.ts.",
    "// Do not edit this file manually.",
    "",
  ].join("\n");

  return `${header}${imports.join("\n")}\n\nexport const ${exportName} = {\n${setBlocks.join("\n")}\n} as const;\n`;
}

async function main(): Promise<void> {
  const [questFiles, infoFiles] = await Promise.all([
    collectJsonFiles(questsDir),
    collectJsonFiles(informationDir),
  ]);

  const sortedQuestFiles = questFiles.sort((a, b) => a.localeCompare(b));
  const sortedInfoFiles = infoFiles.sort((a, b) => a.localeCompare(b));

  if (sortedQuestFiles.length === 0) {
    throw new Error(`No JSON files found in ${questsDir}`);
  }

  if (sortedInfoFiles.length === 0) {
    throw new Error(`No JSON files found in ${informationDir}`);
  }

  const questsSource = await buildQuestModule({
    exportName: "Quests",
    importRoot: "../Quests",
    files: sortedQuestFiles,
  });

  const informationSource = buildInformationModule({
    exportName: "Information",
    importRoot: "../Information",
    files: sortedInfoFiles,
  });

  await Promise.all([
    fs.writeFile(questsDataFile, questsSource, "utf8"),
    fs.writeFile(informationDataFile, informationSource, "utf8"),
  ]);

  console.log(
    `Updated ${questsDataFile} (${sortedQuestFiles.length} files) and ${informationDataFile} (${sortedInfoFiles.length} files).`,
  );
}

main().catch((error: unknown) => {
  const message = error instanceof Error ? error.message : String(error);
  console.error(message);
  process.exit(1);
});