import { Quests } from './QuestsData.js';
import { Information } from './InformationData.js';
import EQOAzones from '../Map/Zones.js';

export { Quests, Information };
export const Map = EQOAzones;

export const Images = {
  city_maps_Fayspire: new URL("../images/city_maps/Fayspire.png", import.meta.url).href,
  city_maps_Freeport: new URL("../images/city_maps/Freeport.png", import.meta.url).href,
  city_maps_Grobb: new URL("../images/city_maps/Grobb.png", import.meta.url).href,
  city_maps_Halas: new URL("../images/city_maps/Halas.png", import.meta.url).href,
  city_maps_Highbourne: new URL("../images/city_maps/Highbourne.png", import.meta.url).href,
  city_maps_KlikAnon: new URL("../images/city_maps/KlikAnon.png", import.meta.url).href,
  city_maps_Moradhim: new URL("../images/city_maps/Moradhim.png", import.meta.url).href,
  city_maps_Neriak_Nektulos: new URL("../images/city_maps/Neriak-Nektulos.png", import.meta.url).href,
  city_maps_Oggok: new URL("../images/city_maps/Oggok.png", import.meta.url).href,
  city_maps_Qeynos: new URL("../images/city_maps/Qeynos.png", import.meta.url).href,
  city_maps_Rivervale: new URL("../images/city_maps/Rivervale.png", import.meta.url).href,
  city_maps_Surefall_Glade: new URL("../images/city_maps/Surefall_Glade.png", import.meta.url).href,
  city_maps_Tethelin: new URL("../images/city_maps/Tethelin.png", import.meta.url).href,
  cons_con_darkblue: new URL("../images/cons/con_darkblue.png", import.meta.url).href,
  cons_con_green: new URL("../images/cons/con_green.png", import.meta.url).href,
  cons_con_lightblue: new URL("../images/cons/con_lightblue.png", import.meta.url).href,
  cons_con_red: new URL("../images/cons/con_red.png", import.meta.url).href,
  cons_con_white: new URL("../images/cons/con_white.png", import.meta.url).href,
  cons_con_yellow: new URL("../images/cons/con_yellow.png", import.meta.url).href,
  EOQA_Map_BG: new URL("../images/EOQA_Map_BG.png", import.meta.url).href,
  epic_weapons_49_Bard_Rapier: new URL("../images/epic_weapons/49/Bard_Rapier.jpg", import.meta.url).href,
  epic_weapons_49_Bard_Sabre: new URL("../images/epic_weapons/49/Bard_Sabre.jpg", import.meta.url).href,
  epic_weapons_49_Cleric_Greathammer: new URL("../images/epic_weapons/49/Cleric_Greathammer.jpg", import.meta.url).href,
  epic_weapons_49_Cleric_Hammer: new URL("../images/epic_weapons/49/Cleric_Hammer.jpg", import.meta.url).href,
  epic_weapons_49_Druid_Scimitar: new URL("../images/epic_weapons/49/Druid_Scimitar.jpg", import.meta.url).href,
  epic_weapons_49_Druid_Staff: new URL("../images/epic_weapons/49/Druid_Staff.jpg", import.meta.url).href,
  epic_weapons_49_Enchanter_Rod: new URL("../images/epic_weapons/49/Enchanter_Rod.jpg", import.meta.url).href,
  epic_weapons_49_Enchanter_Staff: new URL("../images/epic_weapons/49/Enchanter_Staff.jpg", import.meta.url).href,
  epic_weapons_49_Magician_Rod: new URL("../images/epic_weapons/49/Magician_Rod.jpg", import.meta.url).href,
  epic_weapons_49_Magician_Staff: new URL("../images/epic_weapons/49/Magician_Staff.jpg", import.meta.url).href,
  epic_weapons_49_Monk_Knuckles: new URL("../images/epic_weapons/49/Monk_Knuckles.jpg", import.meta.url).href,
  epic_weapons_49_Monk_Staff: new URL("../images/epic_weapons/49/Monk_Staff.jpg", import.meta.url).href,
  epic_weapons_49_Necromancer_Sickle: new URL("../images/epic_weapons/49/Necromancer_Sickle.jpg", import.meta.url).href,
  epic_weapons_49_Necromancer_Totem: new URL("../images/epic_weapons/49/Necromancer_Totem.jpg", import.meta.url).href,
  epic_weapons_49_Paladin_Greatsword: new URL("../images/epic_weapons/49/Paladin_Greatsword.jpg", import.meta.url).href,
  epic_weapons_49_Paladin_Warhammer: new URL("../images/epic_weapons/49/Paladin_Warhammer.jpg", import.meta.url).href,
  epic_weapons_49_Ranger_Longsword: new URL("../images/epic_weapons/49/Ranger_Longsword.jpg", import.meta.url).href,
  epic_weapons_49_Ranger_Scimitar: new URL("../images/epic_weapons/49/Ranger_Scimitar.jpg", import.meta.url).href,
  epic_weapons_49_Rogue_Dagger: new URL("../images/epic_weapons/49/Rogue_Dagger.jpg", import.meta.url).href,
  epic_weapons_49_Rogue_Stiletto: new URL("../images/epic_weapons/49/Rogue_Stiletto.jpg", import.meta.url).href,
  epic_weapons_49_Shadowknight_Greatsword: new URL("../images/epic_weapons/49/Shadowknight_Greatsword.jpg", import.meta.url).href,
  epic_weapons_49_Shadowknight_Polearm: new URL("../images/epic_weapons/49/Shadowknight_Polearm.jpg", import.meta.url).href,
  epic_weapons_49_Shaman_Club: new URL("../images/epic_weapons/49/Shaman_Club.jpg", import.meta.url).href,
  epic_weapons_49_Shaman_Spear: new URL("../images/epic_weapons/49/Shaman_Spear.jpg", import.meta.url).href,
  epic_weapons_49_Warrior_Greataxe: new URL("../images/epic_weapons/49/Warrior_Greataxe.jpg", import.meta.url).href,
  epic_weapons_49_Warrior_Longsword: new URL("../images/epic_weapons/49/Warrior_Longsword.jpg", import.meta.url).href,
  epic_weapons_49_Wizard_Rod: new URL("../images/epic_weapons/49/Wizard_Rod.jpg", import.meta.url).href,
  epic_weapons_49_Wizard_Staff: new URL("../images/epic_weapons/49/Wizard_Staff.jpg", import.meta.url).href,
  EQOA_BG: new URL("../images/EQOA_BG.png", import.meta.url).href,
  EQOA_Map: new URL("../images/EQOA_Map.png", import.meta.url).href,
  EQOA_Norrath: new URL("../images/EQOA_Norrath.png", import.meta.url).href,
  quests_35_idol_of_lust: new URL("../images/quests/35_idol_of_lust.png", import.meta.url).href,
  quests_35_idol_of_malice: new URL("../images/quests/35_idol_of_malice.png", import.meta.url).href,
  weres_bearwere: new URL("../images/weres/bearwere.png", import.meta.url).href,
  weres_gatorwere: new URL("../images/weres/gatorwere.png", import.meta.url).href,
  weres_lionwere: new URL("../images/weres/lionwere.png", import.meta.url).href,
  weres_ratwere: new URL("../images/weres/ratwere.png", import.meta.url).href,
  weres_vampire: new URL("../images/weres/vampire.png", import.meta.url).href,
  weres_werehunter: new URL("../images/weres/werehunter.png", import.meta.url).href,
  weres_wolfwere: new URL("../images/weres/wolfwere.png", import.meta.url).href,
} as const;

export default { Quests, Information, Map, Images };