// This file is auto-generated by scripts/generate-json-exports.ts.
// Do not edit this file manually.
import type { CMSData } from './cms.js';
import type {
  ArmorItemsData,
  CraftingItemsData,
  GemsItemsData,
  HeldItemsData,
  JewelryItemsData,
  MiscellaneousItemsData,
  UnknownItemsData,
  WeaponsItemsData,
} from './items.js';
import type { SpellsData } from './spells.js';
import Information_databases_cms_alchemist from '../Information/databases/cms/alchemist.json' with { type: "json" };
import Information_databases_cms_archetype from '../Information/databases/cms/archetype.json' with { type: "json" };
import Information_databases_cms_bard from '../Information/databases/cms/bard.json' with { type: "json" };
import Information_databases_cms_cleric from '../Information/databases/cms/cleric.json' with { type: "json" };
import Information_databases_cms_druid from '../Information/databases/cms/druid.json' with { type: "json" };
import Information_databases_cms_enchanter from '../Information/databases/cms/enchanter.json' with { type: "json" };
import Information_databases_cms_general from '../Information/databases/cms/general.json' with { type: "json" };
import Information_databases_cms_magician from '../Information/databases/cms/magician.json' with { type: "json" };
import Information_databases_cms_monk from '../Information/databases/cms/monk.json' with { type: "json" };
import Information_databases_cms_necromancer from '../Information/databases/cms/necromancer.json' with { type: "json" };
import Information_databases_cms_paladin from '../Information/databases/cms/paladin.json' with { type: "json" };
import Information_databases_cms_racial from '../Information/databases/cms/racial.json' with { type: "json" };
import Information_databases_cms_ranger from '../Information/databases/cms/ranger.json' with { type: "json" };
import Information_databases_cms_rogue from '../Information/databases/cms/rogue.json' with { type: "json" };
import Information_databases_cms_shadowknight from '../Information/databases/cms/shadowknight.json' with { type: "json" };
import Information_databases_cms_shaman from '../Information/databases/cms/shaman.json' with { type: "json" };
import Information_databases_cms_warrior from '../Information/databases/cms/warrior.json' with { type: "json" };
import Information_databases_cms_were from '../Information/databases/cms/were.json' with { type: "json" };
import Information_databases_cms_werehunter from '../Information/databases/cms/werehunter.json' with { type: "json" };
import Information_databases_cms_wizard from '../Information/databases/cms/wizard.json' with { type: "json" };
import Information_databases_items_armor from '../Information/databases/items/armor.json' with { type: "json" };
import Information_databases_items_crafting from '../Information/databases/items/crafting.json' with { type: "json" };
import Information_databases_items_gems from '../Information/databases/items/gems.json' with { type: "json" };
import Information_databases_items_held from '../Information/databases/items/held.json' with { type: "json" };
import Information_databases_items_jewelry from '../Information/databases/items/jewelry.json' with { type: "json" };
import Information_databases_items_miscellaneous from '../Information/databases/items/miscellaneous.json' with { type: "json" };
import Information_databases_items_unknown from '../Information/databases/items/unknown.json' with { type: "json" };
import Information_databases_items_weapons from '../Information/databases/items/weapons.json' with { type: "json" };
import Information_databases_spells_alchemist from '../Information/databases/spells/alchemist.json' with { type: "json" };
import Information_databases_spells_bard from '../Information/databases/spells/bard.json' with { type: "json" };
import Information_databases_spells_cleric from '../Information/databases/spells/cleric.json' with { type: "json" };
import Information_databases_spells_druid from '../Information/databases/spells/druid.json' with { type: "json" };
import Information_databases_spells_enchanter from '../Information/databases/spells/enchanter.json' with { type: "json" };
import Information_databases_spells_magician from '../Information/databases/spells/magician.json' with { type: "json" };
import Information_databases_spells_monk from '../Information/databases/spells/monk.json' with { type: "json" };
import Information_databases_spells_necromancer from '../Information/databases/spells/necromancer.json' with { type: "json" };
import Information_databases_spells_paladin from '../Information/databases/spells/paladin.json' with { type: "json" };
import Information_databases_spells_ranger from '../Information/databases/spells/ranger.json' with { type: "json" };
import Information_databases_spells_rogue from '../Information/databases/spells/rogue.json' with { type: "json" };
import Information_databases_spells_shadowknight from '../Information/databases/spells/shadowknight.json' with { type: "json" };
import Information_databases_spells_shaman from '../Information/databases/spells/shaman.json' with { type: "json" };
import Information_databases_spells_warrior from '../Information/databases/spells/warrior.json' with { type: "json" };
import Information_databases_spells_wizard from '../Information/databases/spells/wizard.json' with { type: "json" };
import Information_epics from '../Information/epics.json' with { type: "json" };
import Information_how_to_play from '../Information/how_to_play.json' with { type: "json" };
import Information_mastercraft from '../Information/mastercraft.json' with { type: "json" };
import Information_race_class_stats from '../Information/race_class_stats.json' with { type: "json" };
import Information_starting_cities from '../Information/starting_cities.json' with { type: "json" };
import Information_xp_camps from '../Information/xp_camps.json' with { type: "json" };

export const Information = {
  'databases/cms/alchemist': Information_databases_cms_alchemist as unknown as CMSData,
  'databases/cms/archetype': Information_databases_cms_archetype as unknown as CMSData,
  'databases/cms/bard': Information_databases_cms_bard as unknown as CMSData,
  'databases/cms/cleric': Information_databases_cms_cleric as unknown as CMSData,
  'databases/cms/druid': Information_databases_cms_druid as unknown as CMSData,
  'databases/cms/enchanter': Information_databases_cms_enchanter as unknown as CMSData,
  'databases/cms/general': Information_databases_cms_general as unknown as CMSData,
  'databases/cms/magician': Information_databases_cms_magician as unknown as CMSData,
  'databases/cms/monk': Information_databases_cms_monk as unknown as CMSData,
  'databases/cms/necromancer': Information_databases_cms_necromancer as unknown as CMSData,
  'databases/cms/paladin': Information_databases_cms_paladin as unknown as CMSData,
  'databases/cms/racial': Information_databases_cms_racial as unknown as CMSData,
  'databases/cms/ranger': Information_databases_cms_ranger as unknown as CMSData,
  'databases/cms/rogue': Information_databases_cms_rogue as unknown as CMSData,
  'databases/cms/shadowknight': Information_databases_cms_shadowknight as unknown as CMSData,
  'databases/cms/shaman': Information_databases_cms_shaman as unknown as CMSData,
  'databases/cms/warrior': Information_databases_cms_warrior as unknown as CMSData,
  'databases/cms/were': Information_databases_cms_were as unknown as CMSData,
  'databases/cms/werehunter': Information_databases_cms_werehunter as unknown as CMSData,
  'databases/cms/wizard': Information_databases_cms_wizard as unknown as CMSData,
  'databases/items/armor': Information_databases_items_armor as unknown as ArmorItemsData,
  'databases/items/crafting': Information_databases_items_crafting as unknown as CraftingItemsData,
  'databases/items/gems': Information_databases_items_gems as unknown as GemsItemsData,
  'databases/items/held': Information_databases_items_held as unknown as HeldItemsData,
  'databases/items/jewelry': Information_databases_items_jewelry as unknown as JewelryItemsData,
  'databases/items/miscellaneous': Information_databases_items_miscellaneous as unknown as MiscellaneousItemsData,
  'databases/items/unknown': Information_databases_items_unknown as unknown as UnknownItemsData,
  'databases/items/weapons': Information_databases_items_weapons as unknown as WeaponsItemsData,
  'databases/spells/alchemist': Information_databases_spells_alchemist as unknown as SpellsData,
  'databases/spells/bard': Information_databases_spells_bard as unknown as SpellsData,
  'databases/spells/cleric': Information_databases_spells_cleric as unknown as SpellsData,
  'databases/spells/druid': Information_databases_spells_druid as unknown as SpellsData,
  'databases/spells/enchanter': Information_databases_spells_enchanter as unknown as SpellsData,
  'databases/spells/magician': Information_databases_spells_magician as unknown as SpellsData,
  'databases/spells/monk': Information_databases_spells_monk as unknown as SpellsData,
  'databases/spells/necromancer': Information_databases_spells_necromancer as unknown as SpellsData,
  'databases/spells/paladin': Information_databases_spells_paladin as unknown as SpellsData,
  'databases/spells/ranger': Information_databases_spells_ranger as unknown as SpellsData,
  'databases/spells/rogue': Information_databases_spells_rogue as unknown as SpellsData,
  'databases/spells/shadowknight': Information_databases_spells_shadowknight as unknown as SpellsData,
  'databases/spells/shaman': Information_databases_spells_shaman as unknown as SpellsData,
  'databases/spells/warrior': Information_databases_spells_warrior as unknown as SpellsData,
  'databases/spells/wizard': Information_databases_spells_wizard as unknown as SpellsData,
  'epics': Information_epics,
  'how_to_play': Information_how_to_play,
  'mastercraft': Information_mastercraft,
  'race_class_stats': Information_race_class_stats,
  'starting_cities': Information_starting_cities,
  'xp_camps': Information_xp_camps,
} as const;
