// This file is auto-generated by scripts/generate-json-exports.ts.
// Do not edit this file manually.
import Information_databases_cms_alchemist from '../Information/databases/cms/alchemist.json' with { type: "json" };
import Information_databases_cms_archetype from '../Information/databases/cms/archetype.json' with { type: "json" };
import Information_databases_cms_bard from '../Information/databases/cms/bard.json' with { type: "json" };
import Information_databases_cms_cleric from '../Information/databases/cms/cleric.json' with { type: "json" };
import Information_databases_cms_druid from '../Information/databases/cms/druid.json' with { type: "json" };
import Information_databases_cms_enchanter from '../Information/databases/cms/enchanter.json' with { type: "json" };
import Information_databases_cms_general from '../Information/databases/cms/general.json' with { type: "json" };
import Information_databases_cms_magician from '../Information/databases/cms/magician.json' with { type: "json" };
import Information_databases_cms_monk from '../Information/databases/cms/monk.json' with { type: "json" };
import Information_databases_cms_necromancer from '../Information/databases/cms/necromancer.json' with { type: "json" };
import Information_databases_cms_paladin from '../Information/databases/cms/paladin.json' with { type: "json" };
import Information_databases_cms_racial from '../Information/databases/cms/racial.json' with { type: "json" };
import Information_databases_cms_ranger from '../Information/databases/cms/ranger.json' with { type: "json" };
import Information_databases_cms_rogue from '../Information/databases/cms/rogue.json' with { type: "json" };
import Information_databases_cms_shadowknight from '../Information/databases/cms/shadowknight.json' with { type: "json" };
import Information_databases_cms_shaman from '../Information/databases/cms/shaman.json' with { type: "json" };
import Information_databases_cms_warrior from '../Information/databases/cms/warrior.json' with { type: "json" };
import Information_databases_cms_were from '../Information/databases/cms/were.json' with { type: "json" };
import Information_databases_cms_werehunter from '../Information/databases/cms/werehunter.json' with { type: "json" };
import Information_databases_cms_wizard from '../Information/databases/cms/wizard.json' with { type: "json" };
import Information_databases_items_items_list from '../Information/databases/items/items_list.json' with { type: "json" };
import Information_databases_spells_alchemist from '../Information/databases/spells/alchemist.json' with { type: "json" };
import Information_databases_spells_bard from '../Information/databases/spells/bard.json' with { type: "json" };
import Information_databases_spells_cleric from '../Information/databases/spells/cleric.json' with { type: "json" };
import Information_databases_spells_druid from '../Information/databases/spells/druid.json' with { type: "json" };
import Information_databases_spells_enchanter from '../Information/databases/spells/enchanter.json' with { type: "json" };
import Information_databases_spells_magician from '../Information/databases/spells/magician.json' with { type: "json" };
import Information_databases_spells_monk from '../Information/databases/spells/monk.json' with { type: "json" };
import Information_databases_spells_necromancer from '../Information/databases/spells/necromancer.json' with { type: "json" };
import Information_databases_spells_paladin from '../Information/databases/spells/paladin.json' with { type: "json" };
import Information_databases_spells_ranger from '../Information/databases/spells/ranger.json' with { type: "json" };
import Information_databases_spells_rogue from '../Information/databases/spells/rogue.json' with { type: "json" };
import Information_databases_spells_shadowknight from '../Information/databases/spells/shadowknight.json' with { type: "json" };
import Information_databases_spells_shaman from '../Information/databases/spells/shaman.json' with { type: "json" };
import Information_databases_spells_warrior from '../Information/databases/spells/warrior.json' with { type: "json" };
import Information_databases_spells_wizard from '../Information/databases/spells/wizard.json' with { type: "json" };
import Information_epics from '../Information/epics.json' with { type: "json" };
import Information_how_to_play from '../Information/how_to_play.json' with { type: "json" };
import Information_race_class_stats from '../Information/race_class_stats.json' with { type: "json" };
import Information_starting_cities from '../Information/starting_cities.json' with { type: "json" };
import Information_xp_camps from '../Information/xp_camps.json' with { type: "json" };

export const Information = {
  'databases/cms/alchemist': Information_databases_cms_alchemist,
  'databases/cms/archetype': Information_databases_cms_archetype,
  'databases/cms/bard': Information_databases_cms_bard,
  'databases/cms/cleric': Information_databases_cms_cleric,
  'databases/cms/druid': Information_databases_cms_druid,
  'databases/cms/enchanter': Information_databases_cms_enchanter,
  'databases/cms/general': Information_databases_cms_general,
  'databases/cms/magician': Information_databases_cms_magician,
  'databases/cms/monk': Information_databases_cms_monk,
  'databases/cms/necromancer': Information_databases_cms_necromancer,
  'databases/cms/paladin': Information_databases_cms_paladin,
  'databases/cms/racial': Information_databases_cms_racial,
  'databases/cms/ranger': Information_databases_cms_ranger,
  'databases/cms/rogue': Information_databases_cms_rogue,
  'databases/cms/shadowknight': Information_databases_cms_shadowknight,
  'databases/cms/shaman': Information_databases_cms_shaman,
  'databases/cms/warrior': Information_databases_cms_warrior,
  'databases/cms/were': Information_databases_cms_were,
  'databases/cms/werehunter': Information_databases_cms_werehunter,
  'databases/cms/wizard': Information_databases_cms_wizard,
  'databases/items/items_list': Information_databases_items_items_list,
  'databases/spells/alchemist': Information_databases_spells_alchemist,
  'databases/spells/bard': Information_databases_spells_bard,
  'databases/spells/cleric': Information_databases_spells_cleric,
  'databases/spells/druid': Information_databases_spells_druid,
  'databases/spells/enchanter': Information_databases_spells_enchanter,
  'databases/spells/magician': Information_databases_spells_magician,
  'databases/spells/monk': Information_databases_spells_monk,
  'databases/spells/necromancer': Information_databases_spells_necromancer,
  'databases/spells/paladin': Information_databases_spells_paladin,
  'databases/spells/ranger': Information_databases_spells_ranger,
  'databases/spells/rogue': Information_databases_spells_rogue,
  'databases/spells/shadowknight': Information_databases_spells_shadowknight,
  'databases/spells/shaman': Information_databases_spells_shaman,
  'databases/spells/warrior': Information_databases_spells_warrior,
  'databases/spells/wizard': Information_databases_spells_wizard,
  'epics': Information_epics,
  'how_to_play': Information_how_to_play,
  'race_class_stats': Information_race_class_stats,
  'starting_cities': Information_starting_cities,
  'xp_camps': Information_xp_camps,
} as const;
