// This file is auto-generated by scripts/generate-json-exports.mjs.
// Do not edit this file manually.
import Information_spells_alchemist from '../Information/spells/alchemist.json' with { type: "json" };
import Information_starting_cities from '../Information/starting_cities.json' with { type: "json" };
import Information_xp_camps from '../Information/xp_camps.json' with { type: "json" };

export const Information = {
  'spells/alchemist': Information_spells_alchemist,
  'starting_cities': Information_starting_cities,
  'xp_camps': Information_xp_camps,
} as const;
