// This file is auto-generated by scripts/generate-json-exports.ts.
// Do not edit this file manually.
import Quests_1_20__meta from '../Quests/1-20/_meta.json' with { type: "json" };
import Quests_1_20_fayspire__meta from '../Quests/1-20/fayspire/_meta.json' with { type: "json" };
import Quests_1_20_fayspire_alchemist from '../Quests/1-20/fayspire/alchemist.json' with { type: "json" };
import Quests_1_20_fayspire_cleric from '../Quests/1-20/fayspire/cleric.json' with { type: "json" };
import Quests_1_20_fayspire_enchanter from '../Quests/1-20/fayspire/enchanter.json' with { type: "json" };
import Quests_1_20_fayspire_magician from '../Quests/1-20/fayspire/magician.json' with { type: "json" };
import Quests_1_20_fayspire_paladin from '../Quests/1-20/fayspire/paladin.json' with { type: "json" };
import Quests_1_20_fayspire_wizard from '../Quests/1-20/fayspire/wizard.json' with { type: "json" };
import Quests_1_20_freeport__meta from '../Quests/1-20/freeport/_meta.json' with { type: "json" };
import Quests_1_20_freeport_alchemist from '../Quests/1-20/freeport/alchemist.json' with { type: "json" };
import Quests_1_20_freeport_bard from '../Quests/1-20/freeport/bard.json' with { type: "json" };
import Quests_1_20_freeport_cleric from '../Quests/1-20/freeport/cleric.json' with { type: "json" };
import Quests_1_20_freeport_enchanter from '../Quests/1-20/freeport/enchanter.json' with { type: "json" };
import Quests_1_20_freeport_magician from '../Quests/1-20/freeport/magician.json' with { type: "json" };
import Quests_1_20_freeport_necromancer from '../Quests/1-20/freeport/necromancer.json' with { type: "json" };
import Quests_1_20_freeport_rogue from '../Quests/1-20/freeport/rogue.json' with { type: "json" };
import Quests_1_20_freeport_shadowknight from '../Quests/1-20/freeport/shadowknight.json' with { type: "json" };
import Quests_1_20_freeport_warrior from '../Quests/1-20/freeport/warrior.json' with { type: "json" };
import Quests_1_20_freeport_wizard from '../Quests/1-20/freeport/wizard.json' with { type: "json" };
import Quests_1_20_grobb__meta from '../Quests/1-20/grobb/_meta.json' with { type: "json" };
import Quests_1_20_grobb_shadowknight from '../Quests/1-20/grobb/shadowknight.json' with { type: "json" };
import Quests_1_20_grobb_shaman from '../Quests/1-20/grobb/shaman.json' with { type: "json" };
import Quests_1_20_grobb_warrior from '../Quests/1-20/grobb/warrior.json' with { type: "json" };
import Quests_1_20_halas__meta from '../Quests/1-20/halas/_meta.json' with { type: "json" };
import Quests_1_20_halas_rogue from '../Quests/1-20/halas/rogue.json' with { type: "json" };
import Quests_1_20_halas_shaman from '../Quests/1-20/halas/shaman.json' with { type: "json" };
import Quests_1_20_halas_warrior from '../Quests/1-20/halas/warrior.json' with { type: "json" };
import Quests_1_20_highbourne__meta from '../Quests/1-20/highbourne/_meta.json' with { type: "json" };
import Quests_1_20_highbourne_alchemist from '../Quests/1-20/highbourne/alchemist.json' with { type: "json" };
import Quests_1_20_highbourne_cleric from '../Quests/1-20/highbourne/cleric.json' with { type: "json" };
import Quests_1_20_highbourne_enchanter from '../Quests/1-20/highbourne/enchanter.json' with { type: "json" };
import Quests_1_20_highbourne_magician from '../Quests/1-20/highbourne/magician.json' with { type: "json" };
import Quests_1_20_highbourne_necromancer from '../Quests/1-20/highbourne/necromancer.json' with { type: "json" };
import Quests_1_20_highbourne_paladin from '../Quests/1-20/highbourne/paladin.json' with { type: "json" };
import Quests_1_20_highbourne_shadowknight from '../Quests/1-20/highbourne/shadowknight.json' with { type: "json" };
import Quests_1_20_highbourne_wizard from '../Quests/1-20/highbourne/wizard.json' with { type: "json" };
import Quests_1_20_klick_anon__meta from '../Quests/1-20/klick-anon/_meta.json' with { type: "json" };
import Quests_1_20_klick_anon_alchemist from '../Quests/1-20/klick-anon/alchemist.json' with { type: "json" };
import Quests_1_20_klick_anon_cleric from '../Quests/1-20/klick-anon/cleric.json' with { type: "json" };
import Quests_1_20_klick_anon_enchanter from '../Quests/1-20/klick-anon/enchanter.json' with { type: "json" };
import Quests_1_20_klick_anon_magician from '../Quests/1-20/klick-anon/magician.json' with { type: "json" };
import Quests_1_20_klick_anon_necromancer from '../Quests/1-20/klick-anon/necromancer.json' with { type: "json" };
import Quests_1_20_klick_anon_rogue from '../Quests/1-20/klick-anon/rogue.json' with { type: "json" };
import Quests_1_20_klick_anon_warrior from '../Quests/1-20/klick-anon/warrior.json' with { type: "json" };
import Quests_1_20_klick_anon_wizard from '../Quests/1-20/klick-anon/wizard.json' with { type: "json" };
import Quests_1_20_moradhim__meta from '../Quests/1-20/moradhim/_meta.json' with { type: "json" };
import Quests_1_20_moradhim_cleric from '../Quests/1-20/moradhim/cleric.json' with { type: "json" };
import Quests_1_20_moradhim_paladin from '../Quests/1-20/moradhim/paladin.json' with { type: "json" };
import Quests_1_20_moradhim_rogue from '../Quests/1-20/moradhim/rogue.json' with { type: "json" };
import Quests_1_20_moradhim_warrior from '../Quests/1-20/moradhim/warrior.json' with { type: "json" };
import Quests_1_20_neriak_nektulos__meta from '../Quests/1-20/neriak-nektulos/_meta.json' with { type: "json" };
import Quests_1_20_neriak_nektulos_alchemist from '../Quests/1-20/neriak-nektulos/alchemist.json' with { type: "json" };
import Quests_1_20_neriak_nektulos_cleric from '../Quests/1-20/neriak-nektulos/cleric.json' with { type: "json" };
import Quests_1_20_neriak_nektulos_enchanter from '../Quests/1-20/neriak-nektulos/enchanter.json' with { type: "json" };
import Quests_1_20_neriak_nektulos_magician from '../Quests/1-20/neriak-nektulos/magician.json' with { type: "json" };
import Quests_1_20_neriak_nektulos_necromancer from '../Quests/1-20/neriak-nektulos/necromancer.json' with { type: "json" };
import Quests_1_20_neriak_nektulos_rogue from '../Quests/1-20/neriak-nektulos/rogue.json' with { type: "json" };
import Quests_1_20_neriak_nektulos_shadowknight from '../Quests/1-20/neriak-nektulos/shadowknight.json' with { type: "json" };
import Quests_1_20_neriak_nektulos_warrior from '../Quests/1-20/neriak-nektulos/warrior.json' with { type: "json" };
import Quests_1_20_neriak_nektulos_wizard from '../Quests/1-20/neriak-nektulos/wizard.json' with { type: "json" };
import Quests_1_20_oggok__meta from '../Quests/1-20/oggok/_meta.json' with { type: "json" };
import Quests_1_20_oggok_necromancer from '../Quests/1-20/oggok/necromancer.json' with { type: "json" };
import Quests_1_20_oggok_shadowknight from '../Quests/1-20/oggok/shadowknight.json' with { type: "json" };
import Quests_1_20_oggok_shaman from '../Quests/1-20/oggok/shaman.json' with { type: "json" };
import Quests_1_20_oggok_warrior from '../Quests/1-20/oggok/warrior.json' with { type: "json" };
import Quests_1_20_qeynos__meta from '../Quests/1-20/qeynos/_meta.json' with { type: "json" };
import Quests_1_20_qeynos_alchemist from '../Quests/1-20/qeynos/alchemist.json' with { type: "json" };
import Quests_1_20_qeynos_bard from '../Quests/1-20/qeynos/bard.json' with { type: "json" };
import Quests_1_20_qeynos_cleric from '../Quests/1-20/qeynos/cleric.json' with { type: "json" };
import Quests_1_20_qeynos_enchanter from '../Quests/1-20/qeynos/enchanter.json' with { type: "json" };
import Quests_1_20_qeynos_magician from '../Quests/1-20/qeynos/magician.json' with { type: "json" };
import Quests_1_20_qeynos_monk from '../Quests/1-20/qeynos/monk.json' with { type: "json" };
import Quests_1_20_qeynos_paladin from '../Quests/1-20/qeynos/paladin.json' with { type: "json" };
import Quests_1_20_qeynos_rogue from '../Quests/1-20/qeynos/rogue.json' with { type: "json" };
import Quests_1_20_qeynos_warrior from '../Quests/1-20/qeynos/warrior.json' with { type: "json" };
import Quests_1_20_qeynos_wizard from '../Quests/1-20/qeynos/wizard.json' with { type: "json" };
import Quests_1_20_rivervale__meta from '../Quests/1-20/rivervale/_meta.json' with { type: "json" };
import Quests_1_20_rivervale_cleric from '../Quests/1-20/rivervale/cleric.json' with { type: "json" };
import Quests_1_20_rivervale_druid from '../Quests/1-20/rivervale/druid.json' with { type: "json" };
import Quests_1_20_rivervale_rogue from '../Quests/1-20/rivervale/rogue.json' with { type: "json" };
import Quests_1_20_rivervale_warrior from '../Quests/1-20/rivervale/warrior.json' with { type: "json" };
import Quests_1_20_surefall_glade__meta from '../Quests/1-20/surefall-glade/_meta.json' with { type: "json" };
import Quests_1_20_surefall_glade_druid from '../Quests/1-20/surefall-glade/druid.json' with { type: "json" };
import Quests_1_20_surefall_glade_ranger from '../Quests/1-20/surefall-glade/ranger.json' with { type: "json" };
import Quests_1_20_tethelin__meta from '../Quests/1-20/tethelin/_meta.json' with { type: "json" };
import Quests_1_20_tethelin_bard from '../Quests/1-20/tethelin/bard.json' with { type: "json" };
import Quests_1_20_tethelin_druid from '../Quests/1-20/tethelin/druid.json' with { type: "json" };
import Quests_1_20_tethelin_ranger from '../Quests/1-20/tethelin/ranger.json' with { type: "json" };
import Quests_1_20_tethelin_rogue from '../Quests/1-20/tethelin/rogue.json' with { type: "json" };
import Quests_17__meta from '../Quests/17/_meta.json' with { type: "json" };
import Quests_17_fayspire from '../Quests/17/fayspire.json' with { type: "json" };
import Quests_17_freeport from '../Quests/17/freeport.json' with { type: "json" };
import Quests_17_grobb from '../Quests/17/grobb.json' with { type: "json" };
import Quests_17_halas from '../Quests/17/halas.json' with { type: "json" };
import Quests_17_highbourne from '../Quests/17/highbourne.json' with { type: "json" };
import Quests_17_highpass from '../Quests/17/highpass.json' with { type: "json" };
import Quests_17_klick_anon from '../Quests/17/klick-anon.json' with { type: "json" };
import Quests_17_moradhim from '../Quests/17/moradhim.json' with { type: "json" };
import Quests_17_neriak_nektulos from '../Quests/17/neriak-nektulos.json' with { type: "json" };
import Quests_17_qeynos from '../Quests/17/qeynos.json' with { type: "json" };
import Quests_17_rivervale from '../Quests/17/rivervale.json' with { type: "json" };
import Quests_23_47__meta from '../Quests/23-47/_meta.json' with { type: "json" };
import Quests_23_47_23 from '../Quests/23-47/23.json' with { type: "json" };
import Quests_23_47_25 from '../Quests/23-47/25.json' with { type: "json" };
import Quests_23_47_27 from '../Quests/23-47/27.json' with { type: "json" };
import Quests_23_47_30 from '../Quests/23-47/30.json' with { type: "json" };
import Quests_23_47_33 from '../Quests/23-47/33.json' with { type: "json" };
import Quests_23_47_35 from '../Quests/23-47/35.json' with { type: "json" };
import Quests_23_47_37 from '../Quests/23-47/37.json' with { type: "json" };
import Quests_23_47_43 from '../Quests/23-47/43.json' with { type: "json" };
import Quests_23_47_45 from '../Quests/23-47/45.json' with { type: "json" };
import Quests_23_47_47 from '../Quests/23-47/47.json' with { type: "json" };
import Quests_30_40_49__meta from '../Quests/30,40,49/_meta.json' with { type: "json" };
import Quests_30_40_49_group_1_good from '../Quests/30,40,49/group-1-good.json' with { type: "json" };
import Quests_30_40_49_group_2_good from '../Quests/30,40,49/group-2-good.json' with { type: "json" };
import Quests_30_40_49_group_3_good from '../Quests/30,40,49/group-3-good.json' with { type: "json" };
import Quests_30_40_49_group_4_evil from '../Quests/30,40,49/group-4-evil.json' with { type: "json" };
import Quests_30_40_49_group_5_evil from '../Quests/30,40,49/group-5-evil.json' with { type: "json" };
import Quests_30_40_49_group_6_evil from '../Quests/30,40,49/group-6-evil.json' with { type: "json" };
import Quests_60__meta from '../Quests/60/_meta.json' with { type: "json" };
import Quests_60_evil_caster from '../Quests/60/evil-caster.json' with { type: "json" };
import Quests_60_evil_healer from '../Quests/60/evil-healer.json' with { type: "json" };
import Quests_60_evil_melee from '../Quests/60/evil-melee.json' with { type: "json" };
import Quests_60_evil_tank from '../Quests/60/evil-tank.json' with { type: "json" };
import Quests_60_good_caster from '../Quests/60/good-caster.json' with { type: "json" };
import Quests_60_good_healer from '../Quests/60/good-healer.json' with { type: "json" };
import Quests_60_good_melee from '../Quests/60/good-melee.json' with { type: "json" };
import Quests_60_good_tank from '../Quests/60/good-tank.json' with { type: "json" };
import Quests_HuntAndGather__meta from '../Quests/HuntAndGather/_meta.json' with { type: "json" };
import Quests_HuntAndGather_crazy_larry from '../Quests/HuntAndGather/crazy-larry.json' with { type: "json" };
import Quests_HuntAndGather_crethley_manor from '../Quests/HuntAndGather/crethley-manor.json' with { type: "json" };
import Quests_HuntAndGather_hunt_and_gather from '../Quests/HuntAndGather/hunt-and-gather.json' with { type: "json" };
import Quests_HuntAndGather_lilara_and_skerg from '../Quests/HuntAndGather/lilara-and-skerg.json' with { type: "json" };
import Quests_HuntAndGather_pickclaw_hunt_and_gather from '../Quests/HuntAndGather/pickclaw-hunt-and-gather.json' with { type: "json" };
import Quests_HuntAndGather_pickclaw_key from '../Quests/HuntAndGather/pickclaw-key.json' with { type: "json" };
import Quests_HuntAndGather_siloth_ring from '../Quests/HuntAndGather/siloth-ring.json' with { type: "json" };
import Quests_HuntAndGather_weak_herbs_and_roots from '../Quests/HuntAndGather/weak-herbs-and-roots.json' with { type: "json" };
import Quests_Misc__meta from '../Quests/Misc/_meta.json' with { type: "json" };
import Quests_Misc_acolyte_of_bristlebane from '../Quests/Misc/acolyte-of-bristlebane.json' with { type: "json" };
import Quests_Misc_anu_village_pet from '../Quests/Misc/anu-village-pet.json' with { type: "json" };
import Quests_Misc_archon_aereth_archon_vetash_and_primeval_elements from '../Quests/Misc/archon-aereth-archon-vetash-and-primeval-elements.json' with { type: "json" };
import Quests_Misc_avatar_of_fear from '../Quests/Misc/avatar-of-fear.json' with { type: "json" };
import Quests_Misc_captain_scilond_anniversary from '../Quests/Misc/captain-scilond-anniversary.json' with { type: "json" };
import Quests_Misc_dawn_maiden from '../Quests/Misc/dawn-maiden.json' with { type: "json" };
import Quests_Misc_dynmath_the_tyrant from '../Quests/Misc/dynmath-the-tyrant.json' with { type: "json" };
import Quests_Misc_fairy_in_a_jug from '../Quests/Misc/fairy-in-a-jug.json' with { type: "json" };
import Quests_Misc_fan_fair_2006 from '../Quests/Misc/fan-fair-2006.json' with { type: "json" };
import Quests_Misc_glonkal from '../Quests/Misc/glonkal.json' with { type: "json" };
import Quests_Misc_grundle from '../Quests/Misc/grundle.json' with { type: "json" };
import Quests_Misc_harbingers_of_khalimet from '../Quests/Misc/harbingers-of-khalimet.json' with { type: "json" };
import Quests_Misc_heather_johns from '../Quests/Misc/heather-johns.json' with { type: "json" };
import Quests_Misc_highbourne_for_the_ring from '../Quests/Misc/highbourne-for-the-ring.json' with { type: "json" };
import Quests_Misc_hulthu_the_dark from '../Quests/Misc/hulthu-the-dark.json' with { type: "json" };
import Quests_Misc_jaeger_mansion from '../Quests/Misc/jaeger-mansion.json' with { type: "json" };
import Quests_Misc_king_xorbb from '../Quests/Misc/king-xorbb.json' with { type: "json" };
import Quests_Misc_kratas from '../Quests/Misc/kratas.json' with { type: "json" };
import Quests_Misc_lady_vox from '../Quests/Misc/lady-vox.json' with { type: "json" };
import Quests_Misc_lord_pickclaw from '../Quests/Misc/lord-pickclaw.json' with { type: "json" };
import Quests_Misc_lord_valkanith from '../Quests/Misc/lord-valkanith.json' with { type: "json" };
import Quests_Misc_neriak_book from '../Quests/Misc/neriak-book.json' with { type: "json" };
import Quests_Misc_overlord_xrag_son_of_xrag_and_bone_sentinel from '../Quests/Misc/overlord-xrag-son-of-xrag-and-bone-sentinel.json' with { type: "json" };
import Quests_Misc_paineel from '../Quests/Misc/paineel.json' with { type: "json" };
import Quests_Misc_qeynosbook from '../Quests/Misc/qeynosbook.json' with { type: "json" };
import Quests_Misc_quintashi from '../Quests/Misc/quintashi.json' with { type: "json" };
import Quests_Misc_radavex from '../Quests/Misc/radavex.json' with { type: "json" };
import Quests_Misc_sea_of_lions from '../Quests/Misc/sea-of-lions.json' with { type: "json" };
import Quests_Misc_siliskor from '../Quests/Misc/siliskor.json' with { type: "json" };
import Quests_Misc_skahyir from '../Quests/Misc/skahyir.json' with { type: "json" };
import Quests_Misc_snowgrin from '../Quests/Misc/snowgrin.json' with { type: "json" };
import Quests_Misc_spider_queen_aszec from '../Quests/Misc/spider-queen-aszec.json' with { type: "json" };
import Quests_Misc_stat_boost_quests from '../Quests/Misc/stat-boost-quests.json' with { type: "json" };
import Quests_Misc_stone_of_morthalis from '../Quests/Misc/stone-of-morthalis.json' with { type: "json" };
import Quests_Misc_terrorantula from '../Quests/Misc/terrorantula.json' with { type: "json" };
import Quests_Misc_the_illusionist from '../Quests/Misc/the-illusionist.json' with { type: "json" };
import Quests_Misc_the_temple_of_light from '../Quests/Misc/the-temple-of-light.json' with { type: "json" };
import Quests_Misc_the_theatre from '../Quests/Misc/the-theatre.json' with { type: "json" };
import Quests_Misc_the_truearrow from '../Quests/Misc/the-truearrow.json' with { type: "json" };
import Quests_Misc_thenon_the_wise from '../Quests/Misc/thenon-the-wise.json' with { type: "json" };
import Quests_Misc_toxxulia from '../Quests/Misc/toxxulia.json' with { type: "json" };
import Quests_Misc_undead_drake_lord from '../Quests/Misc/undead-drake-lord.json' with { type: "json" };
import Quests_Misc_unkempt_war from '../Quests/Misc/unkempt-war.json' with { type: "json" };
import Quests_Misc_west_feerot from '../Quests/Misc/west-feerot.json' with { type: "json" };
import Quests_Misc_zentars_keep_pet from '../Quests/Misc/zentars-keep-pet.json' with { type: "json" };
import Quests_Portal__meta from '../Quests/Portal/_meta.json' with { type: "json" };
import Quests_Portal_envaric_ascension_quest from '../Quests/Portal/envaric-ascension-quest.json' with { type: "json" };
import Quests_Portal_fendren_the_forgotten from '../Quests/Portal/fendren-the-forgotten.json' with { type: "json" };
import Quests_Portal_isle_of_dread from '../Quests/Portal/isle-of-dread.json' with { type: "json" };
import Quests_Portal_plane_of_disease from '../Quests/Portal/plane-of-disease.json' with { type: "json" };
import Quests_Portal_plane_of_sky from '../Quests/Portal/plane-of-sky.json' with { type: "json" };
import Quests_Portal_sarek_the_betrayer_port from '../Quests/Portal/sarek-the-betrayer-port.json' with { type: "json" };
import Quests_Portal_soluseks_eye from '../Quests/Portal/soluseks-eye.json' with { type: "json" };
import Quests_Portal_zaoran_plateau from '../Quests/Portal/zaoran-plateau.json' with { type: "json" };
import Quests_TankExemplar__meta from '../Quests/TankExemplar/_meta.json' with { type: "json" };
import Quests_TankExemplar_paladin from '../Quests/TankExemplar/paladin.json' with { type: "json" };
import Quests_TankExemplar_shadowknight from '../Quests/TankExemplar/shadowknight.json' with { type: "json" };
import Quests_TankExemplar_warrior from '../Quests/TankExemplar/warrior.json' with { type: "json" };
import Quests_Weres__meta from '../Quests/Weres/_meta.json' with { type: "json" };
import Quests_Weres_bearwere from '../Quests/Weres/bearwere.json' with { type: "json" };
import Quests_Weres_gatorwere from '../Quests/Weres/gatorwere.json' with { type: "json" };
import Quests_Weres_lionwere from '../Quests/Weres/lionwere.json' with { type: "json" };
import Quests_Weres_ratwere from '../Quests/Weres/ratwere.json' with { type: "json" };
import Quests_Weres_vampire from '../Quests/Weres/vampire.json' with { type: "json" };
import Quests_Weres_werehunter from '../Quests/Weres/werehunter.json' with { type: "json" };
import Quests_Weres_wolfwere from '../Quests/Weres/wolfwere.json' with { type: "json" };

export const Quests = {
  '1-20': {
    title: Quests_1_20__meta.title ?? "",
    subTitle: Quests_1_20__meta.subTitle ?? "",
    _meta: Quests_1_20__meta,
    'fayspire': {
      _meta: Quests_1_20_fayspire__meta,
      'alchemist': Quests_1_20_fayspire_alchemist,
      'cleric': Quests_1_20_fayspire_cleric,
      'enchanter': Quests_1_20_fayspire_enchanter,
      'magician': Quests_1_20_fayspire_magician,
      'paladin': Quests_1_20_fayspire_paladin,
      'wizard': Quests_1_20_fayspire_wizard,
    },
    'freeport': {
      _meta: Quests_1_20_freeport__meta,
      'alchemist': Quests_1_20_freeport_alchemist,
      'bard': Quests_1_20_freeport_bard,
      'cleric': Quests_1_20_freeport_cleric,
      'enchanter': Quests_1_20_freeport_enchanter,
      'magician': Quests_1_20_freeport_magician,
      'necromancer': Quests_1_20_freeport_necromancer,
      'rogue': Quests_1_20_freeport_rogue,
      'shadowknight': Quests_1_20_freeport_shadowknight,
      'warrior': Quests_1_20_freeport_warrior,
      'wizard': Quests_1_20_freeport_wizard,
    },
    'grobb': {
      _meta: Quests_1_20_grobb__meta,
      'shadowknight': Quests_1_20_grobb_shadowknight,
      'shaman': Quests_1_20_grobb_shaman,
      'warrior': Quests_1_20_grobb_warrior,
    },
    'halas': {
      _meta: Quests_1_20_halas__meta,
      'rogue': Quests_1_20_halas_rogue,
      'shaman': Quests_1_20_halas_shaman,
      'warrior': Quests_1_20_halas_warrior,
    },
    'highbourne': {
      _meta: Quests_1_20_highbourne__meta,
      'alchemist': Quests_1_20_highbourne_alchemist,
      'cleric': Quests_1_20_highbourne_cleric,
      'enchanter': Quests_1_20_highbourne_enchanter,
      'magician': Quests_1_20_highbourne_magician,
      'necromancer': Quests_1_20_highbourne_necromancer,
      'paladin': Quests_1_20_highbourne_paladin,
      'shadowknight': Quests_1_20_highbourne_shadowknight,
      'wizard': Quests_1_20_highbourne_wizard,
    },
    'klick-anon': {
      _meta: Quests_1_20_klick_anon__meta,
      'alchemist': Quests_1_20_klick_anon_alchemist,
      'cleric': Quests_1_20_klick_anon_cleric,
      'enchanter': Quests_1_20_klick_anon_enchanter,
      'magician': Quests_1_20_klick_anon_magician,
      'necromancer': Quests_1_20_klick_anon_necromancer,
      'rogue': Quests_1_20_klick_anon_rogue,
      'warrior': Quests_1_20_klick_anon_warrior,
      'wizard': Quests_1_20_klick_anon_wizard,
    },
    'moradhim': {
      _meta: Quests_1_20_moradhim__meta,
      'cleric': Quests_1_20_moradhim_cleric,
      'paladin': Quests_1_20_moradhim_paladin,
      'rogue': Quests_1_20_moradhim_rogue,
      'warrior': Quests_1_20_moradhim_warrior,
    },
    'neriak-nektulos': {
      _meta: Quests_1_20_neriak_nektulos__meta,
      'alchemist': Quests_1_20_neriak_nektulos_alchemist,
      'cleric': Quests_1_20_neriak_nektulos_cleric,
      'enchanter': Quests_1_20_neriak_nektulos_enchanter,
      'magician': Quests_1_20_neriak_nektulos_magician,
      'necromancer': Quests_1_20_neriak_nektulos_necromancer,
      'rogue': Quests_1_20_neriak_nektulos_rogue,
      'shadowknight': Quests_1_20_neriak_nektulos_shadowknight,
      'warrior': Quests_1_20_neriak_nektulos_warrior,
      'wizard': Quests_1_20_neriak_nektulos_wizard,
    },
    'oggok': {
      _meta: Quests_1_20_oggok__meta,
      'necromancer': Quests_1_20_oggok_necromancer,
      'shadowknight': Quests_1_20_oggok_shadowknight,
      'shaman': Quests_1_20_oggok_shaman,
      'warrior': Quests_1_20_oggok_warrior,
    },
    'qeynos': {
      _meta: Quests_1_20_qeynos__meta,
      'alchemist': Quests_1_20_qeynos_alchemist,
      'bard': Quests_1_20_qeynos_bard,
      'cleric': Quests_1_20_qeynos_cleric,
      'enchanter': Quests_1_20_qeynos_enchanter,
      'magician': Quests_1_20_qeynos_magician,
      'monk': Quests_1_20_qeynos_monk,
      'paladin': Quests_1_20_qeynos_paladin,
      'rogue': Quests_1_20_qeynos_rogue,
      'warrior': Quests_1_20_qeynos_warrior,
      'wizard': Quests_1_20_qeynos_wizard,
    },
    'rivervale': {
      _meta: Quests_1_20_rivervale__meta,
      'cleric': Quests_1_20_rivervale_cleric,
      'druid': Quests_1_20_rivervale_druid,
      'rogue': Quests_1_20_rivervale_rogue,
      'warrior': Quests_1_20_rivervale_warrior,
    },
    'surefall-glade': {
      _meta: Quests_1_20_surefall_glade__meta,
      'druid': Quests_1_20_surefall_glade_druid,
      'ranger': Quests_1_20_surefall_glade_ranger,
    },
    'tethelin': {
      _meta: Quests_1_20_tethelin__meta,
      'bard': Quests_1_20_tethelin_bard,
      'druid': Quests_1_20_tethelin_druid,
      'ranger': Quests_1_20_tethelin_ranger,
      'rogue': Quests_1_20_tethelin_rogue,
    },
  },
  '17': {
    title: Quests_17__meta.title ?? "",
    subTitle: Quests_17__meta.subTitle ?? "",
    _meta: Quests_17__meta,
    'fayspire': Quests_17_fayspire,
    'freeport': Quests_17_freeport,
    'grobb': Quests_17_grobb,
    'halas': Quests_17_halas,
    'highbourne': Quests_17_highbourne,
    'highpass': Quests_17_highpass,
    'klick-anon': Quests_17_klick_anon,
    'moradhim': Quests_17_moradhim,
    'neriak-nektulos': Quests_17_neriak_nektulos,
    'qeynos': Quests_17_qeynos,
    'rivervale': Quests_17_rivervale,
  },
  '23-47': {
    title: Quests_23_47__meta.title ?? "",
    subTitle: Quests_23_47__meta.subTitle ?? "",
    _meta: Quests_23_47__meta,
    '23': Quests_23_47_23,
    '25': Quests_23_47_25,
    '27': Quests_23_47_27,
    '30': Quests_23_47_30,
    '33': Quests_23_47_33,
    '35': Quests_23_47_35,
    '37': Quests_23_47_37,
    '43': Quests_23_47_43,
    '45': Quests_23_47_45,
    '47': Quests_23_47_47,
  },
  '30,40,49': {
    title: Quests_30_40_49__meta.title ?? "",
    subTitle: Quests_30_40_49__meta.subTitle ?? "",
    _meta: Quests_30_40_49__meta,
    'group-1-good': Quests_30_40_49_group_1_good,
    'group-2-good': Quests_30_40_49_group_2_good,
    'group-3-good': Quests_30_40_49_group_3_good,
    'group-4-evil': Quests_30_40_49_group_4_evil,
    'group-5-evil': Quests_30_40_49_group_5_evil,
    'group-6-evil': Quests_30_40_49_group_6_evil,
  },
  '60': {
    title: Quests_60__meta.title ?? "",
    subTitle: Quests_60__meta.subTitle ?? "",
    _meta: Quests_60__meta,
    'evil-caster': Quests_60_evil_caster,
    'evil-healer': Quests_60_evil_healer,
    'evil-melee': Quests_60_evil_melee,
    'evil-tank': Quests_60_evil_tank,
    'good-caster': Quests_60_good_caster,
    'good-healer': Quests_60_good_healer,
    'good-melee': Quests_60_good_melee,
    'good-tank': Quests_60_good_tank,
  },
  'HuntAndGather': {
    title: Quests_HuntAndGather__meta.title ?? "",
    subTitle: Quests_HuntAndGather__meta.subTitle ?? "",
    _meta: Quests_HuntAndGather__meta,
    'crazy-larry': Quests_HuntAndGather_crazy_larry,
    'crethley-manor': Quests_HuntAndGather_crethley_manor,
    'hunt-and-gather': Quests_HuntAndGather_hunt_and_gather,
    'lilara-and-skerg': Quests_HuntAndGather_lilara_and_skerg,
    'pickclaw-hunt-and-gather': Quests_HuntAndGather_pickclaw_hunt_and_gather,
    'pickclaw-key': Quests_HuntAndGather_pickclaw_key,
    'siloth-ring': Quests_HuntAndGather_siloth_ring,
    'weak-herbs-and-roots': Quests_HuntAndGather_weak_herbs_and_roots,
  },
  'Misc': {
    title: Quests_Misc__meta.title ?? "",
    subTitle: Quests_Misc__meta.subTitle ?? "",
    _meta: Quests_Misc__meta,
    'acolyte-of-bristlebane': Quests_Misc_acolyte_of_bristlebane,
    'anu-village-pet': Quests_Misc_anu_village_pet,
    'archon-aereth-archon-vetash-and-primeval-elements': Quests_Misc_archon_aereth_archon_vetash_and_primeval_elements,
    'avatar-of-fear': Quests_Misc_avatar_of_fear,
    'captain-scilond-anniversary': Quests_Misc_captain_scilond_anniversary,
    'dawn-maiden': Quests_Misc_dawn_maiden,
    'dynmath-the-tyrant': Quests_Misc_dynmath_the_tyrant,
    'fairy-in-a-jug': Quests_Misc_fairy_in_a_jug,
    'fan-fair-2006': Quests_Misc_fan_fair_2006,
    'glonkal': Quests_Misc_glonkal,
    'grundle': Quests_Misc_grundle,
    'harbingers-of-khalimet': Quests_Misc_harbingers_of_khalimet,
    'heather-johns': Quests_Misc_heather_johns,
    'highbourne-for-the-ring': Quests_Misc_highbourne_for_the_ring,
    'hulthu-the-dark': Quests_Misc_hulthu_the_dark,
    'jaeger-mansion': Quests_Misc_jaeger_mansion,
    'king-xorbb': Quests_Misc_king_xorbb,
    'kratas': Quests_Misc_kratas,
    'lady-vox': Quests_Misc_lady_vox,
    'lord-pickclaw': Quests_Misc_lord_pickclaw,
    'lord-valkanith': Quests_Misc_lord_valkanith,
    'neriak-book': Quests_Misc_neriak_book,
    'overlord-xrag-son-of-xrag-and-bone-sentinel': Quests_Misc_overlord_xrag_son_of_xrag_and_bone_sentinel,
    'paineel': Quests_Misc_paineel,
    'qeynosbook': Quests_Misc_qeynosbook,
    'quintashi': Quests_Misc_quintashi,
    'radavex': Quests_Misc_radavex,
    'sea-of-lions': Quests_Misc_sea_of_lions,
    'siliskor': Quests_Misc_siliskor,
    'skahyir': Quests_Misc_skahyir,
    'snowgrin': Quests_Misc_snowgrin,
    'spider-queen-aszec': Quests_Misc_spider_queen_aszec,
    'stat-boost-quests': Quests_Misc_stat_boost_quests,
    'stone-of-morthalis': Quests_Misc_stone_of_morthalis,
    'terrorantula': Quests_Misc_terrorantula,
    'the-illusionist': Quests_Misc_the_illusionist,
    'the-temple-of-light': Quests_Misc_the_temple_of_light,
    'the-theatre': Quests_Misc_the_theatre,
    'the-truearrow': Quests_Misc_the_truearrow,
    'thenon-the-wise': Quests_Misc_thenon_the_wise,
    'toxxulia': Quests_Misc_toxxulia,
    'undead-drake-lord': Quests_Misc_undead_drake_lord,
    'unkempt-war': Quests_Misc_unkempt_war,
    'west-feerot': Quests_Misc_west_feerot,
    'zentars-keep-pet': Quests_Misc_zentars_keep_pet,
  },
  'Portal': {
    title: Quests_Portal__meta.title ?? "",
    subTitle: Quests_Portal__meta.subTitle ?? "",
    _meta: Quests_Portal__meta,
    'envaric-ascension-quest': Quests_Portal_envaric_ascension_quest,
    'fendren-the-forgotten': Quests_Portal_fendren_the_forgotten,
    'isle-of-dread': Quests_Portal_isle_of_dread,
    'plane-of-disease': Quests_Portal_plane_of_disease,
    'plane-of-sky': Quests_Portal_plane_of_sky,
    'sarek-the-betrayer-port': Quests_Portal_sarek_the_betrayer_port,
    'soluseks-eye': Quests_Portal_soluseks_eye,
    'zaoran-plateau': Quests_Portal_zaoran_plateau,
  },
  'TankExemplar': {
    title: Quests_TankExemplar__meta.title ?? "",
    subTitle: Quests_TankExemplar__meta.subTitle ?? "",
    _meta: Quests_TankExemplar__meta,
    'paladin': Quests_TankExemplar_paladin,
    'shadowknight': Quests_TankExemplar_shadowknight,
    'warrior': Quests_TankExemplar_warrior,
  },
  'Weres': {
    title: Quests_Weres__meta.title ?? "",
    subTitle: Quests_Weres__meta.subTitle ?? "",
    _meta: Quests_Weres__meta,
    'bearwere': Quests_Weres_bearwere,
    'gatorwere': Quests_Weres_gatorwere,
    'lionwere': Quests_Weres_lionwere,
    'ratwere': Quests_Weres_ratwere,
    'vampire': Quests_Weres_vampire,
    'werehunter': Quests_Weres_werehunter,
    'wolfwere': Quests_Weres_wolfwere,
  },
} as const;
