// This file is auto-generated by scripts/generate-json-exports.mjs.
// Do not edit this file manually.
import Quests_1_20 from '../Quests/1-20.json' with { type: "json" };
import Quests_17 from '../Quests/17.json' with { type: "json" };
import Quests_23_47 from '../Quests/23-47.json' with { type: "json" };
import Quests_30_40_49 from '../Quests/30,40,49.json' with { type: "json" };
import Quests_60 from '../Quests/60.json' with { type: "json" };
import Quests_HuntAndGather from '../Quests/HuntAndGather.json' with { type: "json" };
import Quests_Misc from '../Quests/Misc.json' with { type: "json" };
import Quests_Portal from '../Quests/Portal.json' with { type: "json" };
import Quests_TankExemplar from '../Quests/TankExemplar.json' with { type: "json" };
import Quests_Weres from '../Quests/Weres.json' with { type: "json" };

export const Quests = {
  '1-20': Quests_1_20,
  '17': Quests_17,
  '23-47': Quests_23_47,
  '30-40-49': Quests_30_40_49,
  '60': Quests_60,
  'HuntAndGather': Quests_HuntAndGather,
  'Misc': Quests_Misc,
  'Portal': Quests_Portal,
  'TankExemplar': Quests_TankExemplar,
  'Weres': Quests_Weres,
} as const;
